language: cpp

sudo: required
dist: bionic

compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    update: true
    packages:
      - libplplot-dev
      - libgtkmm-3.0-dev
      - libgtkmm-3.0-doc
      - mm-common
      - autoconf
      - automake
      - libtool
      - doxygen
      - graphviz
      - perl
      - libboost-all-dev

before_install:
  - pyenv global 3.8
  - pip3 install meson ninja

script:
  - |
    autoreconf -fi || exit 1
    mkdir build-autotools || exit 1
    cd build-autotools
    ../configure || exit 1
    make || exit 1
    make check || exit 1
    make distcheck || exit 1
    cd ..
  - |
    mkdir build-meson || exit 1
    cd build-meson
    meson  || exit 1
    ninja || exit 1
    ninja test || exit 1

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

