variables:
  LD_LIBRARY_PATH: /usr/local/lib

trigger: ['master']

jobs:
  - job: osx_64
    pool:
      vmImage: macOS-10.14
    strategy:
      matrix:
        MESON:
          BUILD_SYSTEM: meson
        AUTOTOOLS:
          BUILD_SYSTEM: autotools
    steps:
    - script: |
        set -e -x
        brew update
        brew upgrade
      displayName: Update Homebrew
    - script: |
        set -e -x
        brew install gtkmm3 plplot wget pkg-config doxygen graphviz boost
      displayName: Install dependencies
    - script: |
        set -e -x
        brew install mm-common autoconf automake libtool 
        autoreconf -fi
        brew uninstall mm-common
        ./configure
        make
        make distcheck
      displayName: Test build
      condition: and(succeeded(), eq(variables['BUILD_SYSTEM'], 'autotools'))
    - script: |
        set -e -x
        brew install meson ninja
        TARBALL=$(ls *.tar.gz)
        tar xfz $TARBALL
        cd ${TARBALL%.tar.gz}
        mkdir build
        cd build
        meson ..
        ninja
      displayName: Test dist tarball with other buildsystem
      condition: and(succeeded(), eq(variables['BUILD_SYSTEM'], 'autotools'))
    - script: |
        set -e -x
        brew install meson ninja
        mkdir build
        cd build
        meson ..
        ninja
        ninja dist
      displayName: Test build  
      condition: and(succeeded(), eq(variables['BUILD_SYSTEM'], 'meson'))
    - script: |
        set -e -x
        brew install mm-common autoconf automake libtool
        mv build/meson-dist/gtkmm-plplot*.tar.xz .
        TARBALL=$(ls *.tar.xz)
        tar xfz $TARBALL
        cd ${TARBALL%.tar.xz}
        autoreconf -fi
        brew uninstall mm-common
        ./configure
        make
      displayName: Test dist tarball with other buildsystem
      condition: and(succeeded(), eq(variables['BUILD_SYSTEM'], 'meson'))

  - job: MSYS2
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        x86_64:
          ARCH: x64
          MSYS2_ARCH: x86_64
          MSYS2_DIR: msys64
          MSYSTEM: MINGW64
    steps:
    - script: |
        choco install msys2 --params="/InstallDir:C:\msys64 /NoUpdate /NoPath"
      displayName: Install MSYS2
    - script: |
        set PATH=C:\msys64\usr\bin;%PATH%
        pacman --noconfirm -Syyuu
        pacman --noconfirm -Syuu
      displayName: Update MSYS2
    - script: |
        set PATH=C:\msys64\usr\bin;%PATH%
        pacman --noconfirm -Su mingw-w64-%MSYS2_ARCH%-{gcc,libtool,gtkmm3,boost,cmake,pkg-config} automake autoconf make wget tar pkg-config libtool
      displayName: Install MSYS2 packages
    - script: |
        set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
        bash -lc "wget https://download.gnome.org/sources/mm-common/0.9/mm-common-0.9.12.tar.xz && tar xvfJ mm-common-0.9.12.tar.xz && cd mm-common-0.9.12 && ./configure && make && make install"
      displayName: Install mm-common
    - script: |
        set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
        bash -lc "wget http://lvserver.ugent.be/~schoon/plplot-5.14.0.tar.gz && tar xfz plplot-5.14.0.tar.gz && cd plplot-5.14.0 && cmake -G \"MSYS Makefiles\" -DENABLE_DYNDRIVERS=OFF -DPLD_wingcc=OFF -DCMAKE_INSTALL_PREFIX=/usr/local . && make && make install"
      displayName: Install PLplot
    - script: |
        set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
        bash -lc "cd $SOURCE_HOME && unset BOOST_ROOT && ACLOCAL_PATH=/usr/local/share/aclocal autoreconf -fi && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig ./configure && make && make check && make distcheck"
      displayName: Build Gtkmm-PLplot
      env:
        SOURCE_HOME: $(Build.SourcesDirectory)
